### ISSUE TITLE
error resolveDependencies: Found duplicate dependency key 'undefined' in `index.ts`

### ISSUE THREAD

**Issue by leotm** [leotm/react-native-template-new-architecture#1082]
Pass: https://github.com/leotm/react-native-template-new-architecture/actions/runs/3280636280/jobs/5401659794

Fail: https://github.com/leotm/react-native-template-new-architecture/actions/runs/3280724795/jobs/5401862760

```console
error resolveDependencies: Found duplicate dependency key 'undefined' in /Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/index.ts.
Error: resolveDependencies: Found duplicate dependency key 'undefined' in /Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/index.ts
    at resolveDependencies (/Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/graphOperations.js:484:13)
    at processModule (/Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/graphOperations.js:232:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/leotm/react-native-template-new-architecture/actions/runs/3280724795/jobs/5401862760#step:8:10)6:5)
    at async traverseDependenciesForSingleFile (/Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/graphOperations.js:221:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (/Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/graphOperations.js:204:3)
    at async DeltaCalculator._getChangedDependencies (/Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:208:25)
    at async DeltaCalculator.getDelta (/Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/DeltaCalculator.js:90:[16](https://github.com/leotm/react-native-template-new-architecture/actions/runs/3280724795/jobs/5401862760#step:8:17))
    at async DeltaBundler.buildGraph (/Users/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler.js:56:5)
info Run CLI with --verbose flag for more details.
Error: Process completed with exit code 1.
```

Problem/solutions
- https://github.com/facebook/metro/issues/857

More
- https://github.com/facebook/metro/pull/835

Bonus: Figure inconsistent/flakey part

NB: Already ahead w parts of RN 0.70.4 (`@react-native-community/cli to v9.2.1` [merged](https://github.com/leotm/react-native-template-new-architecture/commit/82141ae83c365acb1411996804aeb511e581da38) in `master` to make available the [asset image fix](https://github.com/react-native-community/cli/pull/1290))
- https://github.com/reactwg/react-native-releases/discussions/38#discussioncomment-3913594

**Comment by leotm** [comment]
It's sneaky transitive 2nd `metro-babel-transformer` ver intro'd in [flipper-server v0.171.1](https://github.com/leotm/react-native-template-new-architecture/commit/f7861f6ed142599b8a049b9ed41b643edfc43174) - revert (3) commits since then let renovate do the rest
